### ISSUE TITLE
Join IG

### ISSUE THREAD

**Issue by VincentDucatteeuw** [CLARIAH/IG-Vocabularies#1]
Hello, I would like to join this IG. (PhD student Ghent University/Ghent Centre for Digital Humanities)

**Comment by menzowindhouwer** [comment]
Hi, you can join here https://groups.google.com/u/1/g/clariah-ig-vocabularies

**Comment by VincentDucatteeuw** [comment]
Thank you for the invitation Menzo. 

Is it also possible to be added to the Slack channel to be up-to-date about ongoing projects and information? My [university mail](https://research.flw.ugent.be/en/vincent.ducatteeuw) can be used for the invitation.
